// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccessControlClient is the client API for AccessControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessControlClient interface {
	// Resource Types
	CreateResourceType(ctx context.Context, in *ResourceType, opts ...grpc.CallOption) (*Empty, error)
	DeleteResourceType(ctx context.Context, in *ResourceTypeKey, opts ...grpc.CallOption) (*Empty, error)
	UpdateResourceType(ctx context.Context, in *ResourceType, opts ...grpc.CallOption) (*Empty, error)
	FindResourceTypes(ctx context.Context, in *FindResourceTypesRequest, opts ...grpc.CallOption) (*ResourceTypes, error)
	// Permission Types
	CreatePermissionType(ctx context.Context, in *PermissionType, opts ...grpc.CallOption) (*Empty, error)
	DeletePermissionType(ctx context.Context, in *DeletePermissionTypeRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdatePermissionType(ctx context.Context, in *PermissionType, opts ...grpc.CallOption) (*Empty, error)
	FindPermissionTypes(ctx context.Context, in *FindPermissionTypesRequest, opts ...grpc.CallOption) (*PermissionTypes, error)
	AssignPermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*Empty, error)
	RevokePermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*Empty, error)
	HasPermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*HasPermissionResponse, error)
	// Permission Graph
	LinkPermissions(ctx context.Context, in *LinkPermissionsRequest, opts ...grpc.CallOption) (*Empty, error)
	UnlinkPermissions(ctx context.Context, in *LinkPermissionsRequest, opts ...grpc.CallOption) (*Empty, error)
	// Resource Graph
	LinkResources(ctx context.Context, in *LinkResourcesRequest, opts ...grpc.CallOption) (*Empty, error)
	UnlinkResources(ctx context.Context, in *LinkResourcesRequest, opts ...grpc.CallOption) (*Empty, error)
}

type accessControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessControlClient(cc grpc.ClientConnInterface) AccessControlClient {
	return &accessControlClient{cc}
}

func (c *accessControlClient) CreateResourceType(ctx context.Context, in *ResourceType, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/CreateResourceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) DeleteResourceType(ctx context.Context, in *ResourceTypeKey, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/DeleteResourceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) UpdateResourceType(ctx context.Context, in *ResourceType, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/UpdateResourceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) FindResourceTypes(ctx context.Context, in *FindResourceTypesRequest, opts ...grpc.CallOption) (*ResourceTypes, error) {
	out := new(ResourceTypes)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/FindResourceTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) CreatePermissionType(ctx context.Context, in *PermissionType, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/CreatePermissionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) DeletePermissionType(ctx context.Context, in *DeletePermissionTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/DeletePermissionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) UpdatePermissionType(ctx context.Context, in *PermissionType, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/UpdatePermissionType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) FindPermissionTypes(ctx context.Context, in *FindPermissionTypesRequest, opts ...grpc.CallOption) (*PermissionTypes, error) {
	out := new(PermissionTypes)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/FindPermissionTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) AssignPermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/AssignPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) RevokePermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/RevokePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) HasPermission(ctx context.Context, in *PermissionBinding, opts ...grpc.CallOption) (*HasPermissionResponse, error) {
	out := new(HasPermissionResponse)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/HasPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) LinkPermissions(ctx context.Context, in *LinkPermissionsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/LinkPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) UnlinkPermissions(ctx context.Context, in *LinkPermissionsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/UnlinkPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) LinkResources(ctx context.Context, in *LinkResourcesRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/LinkResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessControlClient) UnlinkResources(ctx context.Context, in *LinkResourcesRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/access_control.AccessControl/UnlinkResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessControlServer is the server API for AccessControl service.
// All implementations must embed UnimplementedAccessControlServer
// for forward compatibility
type AccessControlServer interface {
	// Resource Types
	CreateResourceType(context.Context, *ResourceType) (*Empty, error)
	DeleteResourceType(context.Context, *ResourceTypeKey) (*Empty, error)
	UpdateResourceType(context.Context, *ResourceType) (*Empty, error)
	FindResourceTypes(context.Context, *FindResourceTypesRequest) (*ResourceTypes, error)
	// Permission Types
	CreatePermissionType(context.Context, *PermissionType) (*Empty, error)
	DeletePermissionType(context.Context, *DeletePermissionTypeRequest) (*Empty, error)
	UpdatePermissionType(context.Context, *PermissionType) (*Empty, error)
	FindPermissionTypes(context.Context, *FindPermissionTypesRequest) (*PermissionTypes, error)
	AssignPermission(context.Context, *PermissionBinding) (*Empty, error)
	RevokePermission(context.Context, *PermissionBinding) (*Empty, error)
	HasPermission(context.Context, *PermissionBinding) (*HasPermissionResponse, error)
	// Permission Graph
	LinkPermissions(context.Context, *LinkPermissionsRequest) (*Empty, error)
	UnlinkPermissions(context.Context, *LinkPermissionsRequest) (*Empty, error)
	// Resource Graph
	LinkResources(context.Context, *LinkResourcesRequest) (*Empty, error)
	UnlinkResources(context.Context, *LinkResourcesRequest) (*Empty, error)
	mustEmbedUnimplementedAccessControlServer()
}

// UnimplementedAccessControlServer must be embedded to have forward compatible implementations.
type UnimplementedAccessControlServer struct {
}

func (UnimplementedAccessControlServer) CreateResourceType(context.Context, *ResourceType) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceType not implemented")
}
func (UnimplementedAccessControlServer) DeleteResourceType(context.Context, *ResourceTypeKey) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceType not implemented")
}
func (UnimplementedAccessControlServer) UpdateResourceType(context.Context, *ResourceType) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceType not implemented")
}
func (UnimplementedAccessControlServer) FindResourceTypes(context.Context, *FindResourceTypesRequest) (*ResourceTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindResourceTypes not implemented")
}
func (UnimplementedAccessControlServer) CreatePermissionType(context.Context, *PermissionType) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermissionType not implemented")
}
func (UnimplementedAccessControlServer) DeletePermissionType(context.Context, *DeletePermissionTypeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePermissionType not implemented")
}
func (UnimplementedAccessControlServer) UpdatePermissionType(context.Context, *PermissionType) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePermissionType not implemented")
}
func (UnimplementedAccessControlServer) FindPermissionTypes(context.Context, *FindPermissionTypesRequest) (*PermissionTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPermissionTypes not implemented")
}
func (UnimplementedAccessControlServer) AssignPermission(context.Context, *PermissionBinding) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignPermission not implemented")
}
func (UnimplementedAccessControlServer) RevokePermission(context.Context, *PermissionBinding) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokePermission not implemented")
}
func (UnimplementedAccessControlServer) HasPermission(context.Context, *PermissionBinding) (*HasPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPermission not implemented")
}
func (UnimplementedAccessControlServer) LinkPermissions(context.Context, *LinkPermissionsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkPermissions not implemented")
}
func (UnimplementedAccessControlServer) UnlinkPermissions(context.Context, *LinkPermissionsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkPermissions not implemented")
}
func (UnimplementedAccessControlServer) LinkResources(context.Context, *LinkResourcesRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkResources not implemented")
}
func (UnimplementedAccessControlServer) UnlinkResources(context.Context, *LinkResourcesRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkResources not implemented")
}
func (UnimplementedAccessControlServer) mustEmbedUnimplementedAccessControlServer() {}

// UnsafeAccessControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessControlServer will
// result in compilation errors.
type UnsafeAccessControlServer interface {
	mustEmbedUnimplementedAccessControlServer()
}

func RegisterAccessControlServer(s grpc.ServiceRegistrar, srv AccessControlServer) {
	s.RegisterService(&AccessControl_ServiceDesc, srv)
}

func _AccessControl_CreateResourceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).CreateResourceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/CreateResourceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).CreateResourceType(ctx, req.(*ResourceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_DeleteResourceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceTypeKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).DeleteResourceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/DeleteResourceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).DeleteResourceType(ctx, req.(*ResourceTypeKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_UpdateResourceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).UpdateResourceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/UpdateResourceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).UpdateResourceType(ctx, req.(*ResourceType))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_FindResourceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindResourceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).FindResourceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/FindResourceTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).FindResourceTypes(ctx, req.(*FindResourceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_CreatePermissionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).CreatePermissionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/CreatePermissionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).CreatePermissionType(ctx, req.(*PermissionType))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_DeletePermissionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePermissionTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).DeletePermissionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/DeletePermissionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).DeletePermissionType(ctx, req.(*DeletePermissionTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_UpdatePermissionType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).UpdatePermissionType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/UpdatePermissionType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).UpdatePermissionType(ctx, req.(*PermissionType))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_FindPermissionTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPermissionTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).FindPermissionTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/FindPermissionTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).FindPermissionTypes(ctx, req.(*FindPermissionTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_AssignPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionBinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).AssignPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/AssignPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).AssignPermission(ctx, req.(*PermissionBinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_RevokePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionBinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).RevokePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/RevokePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).RevokePermission(ctx, req.(*PermissionBinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_HasPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionBinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).HasPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/HasPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).HasPermission(ctx, req.(*PermissionBinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_LinkPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).LinkPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/LinkPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).LinkPermissions(ctx, req.(*LinkPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_UnlinkPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).UnlinkPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/UnlinkPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).UnlinkPermissions(ctx, req.(*LinkPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_LinkResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).LinkResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/LinkResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).LinkResources(ctx, req.(*LinkResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessControl_UnlinkResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServer).UnlinkResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_control.AccessControl/UnlinkResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServer).UnlinkResources(ctx, req.(*LinkResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessControl_ServiceDesc is the grpc.ServiceDesc for AccessControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "access_control.AccessControl",
	HandlerType: (*AccessControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceType",
			Handler:    _AccessControl_CreateResourceType_Handler,
		},
		{
			MethodName: "DeleteResourceType",
			Handler:    _AccessControl_DeleteResourceType_Handler,
		},
		{
			MethodName: "UpdateResourceType",
			Handler:    _AccessControl_UpdateResourceType_Handler,
		},
		{
			MethodName: "FindResourceTypes",
			Handler:    _AccessControl_FindResourceTypes_Handler,
		},
		{
			MethodName: "CreatePermissionType",
			Handler:    _AccessControl_CreatePermissionType_Handler,
		},
		{
			MethodName: "DeletePermissionType",
			Handler:    _AccessControl_DeletePermissionType_Handler,
		},
		{
			MethodName: "UpdatePermissionType",
			Handler:    _AccessControl_UpdatePermissionType_Handler,
		},
		{
			MethodName: "FindPermissionTypes",
			Handler:    _AccessControl_FindPermissionTypes_Handler,
		},
		{
			MethodName: "AssignPermission",
			Handler:    _AccessControl_AssignPermission_Handler,
		},
		{
			MethodName: "RevokePermission",
			Handler:    _AccessControl_RevokePermission_Handler,
		},
		{
			MethodName: "HasPermission",
			Handler:    _AccessControl_HasPermission_Handler,
		},
		{
			MethodName: "LinkPermissions",
			Handler:    _AccessControl_LinkPermissions_Handler,
		},
		{
			MethodName: "UnlinkPermissions",
			Handler:    _AccessControl_UnlinkPermissions_Handler,
		},
		{
			MethodName: "LinkResources",
			Handler:    _AccessControl_LinkResources_Handler,
		},
		{
			MethodName: "UnlinkResources",
			Handler:    _AccessControl_UnlinkResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/api/rpc/proto/access_control.proto",
}
