syntax = "proto3";

package access_control;

option go_package = "github.com/teamyapp/cloud/app/api/rpc/proto";

service AccessControl {
  // Resource Types
  rpc CreateResourceType(ResourceType) returns (Empty);
  rpc DeleteResourceType(ResourceTypeKey) returns (Empty);
  rpc UpdateResourceType(ResourceType) returns (Empty);
  rpc FindResourceTypes(FindResourceTypesRequest) returns (ResourceTypes);

  // Permission Types
  rpc CreatePermissionType(PermissionType) returns (Empty);
  rpc DeletePermissionType(DeletePermissionTypeRequest) returns (Empty);
  rpc UpdatePermissionType(PermissionType) returns (Empty);
  rpc FindPermissionTypes(FindPermissionTypesRequest) returns (PermissionTypes);

  rpc AssignPermission(PermissionBinding) returns (Empty);
  rpc RevokePermission(PermissionBinding) returns (Empty);

  rpc HasPermission(PermissionBinding) returns (HasPermissionResponse);

  // Permission Graph
  rpc LinkPermissions(LinkPermissionsRequest) returns (Empty);
  rpc UnlinkPermissions(LinkPermissionsRequest) returns (Empty);

  // Resource Graph
  rpc LinkResources(LinkResourcesRequest) returns (Empty);
  rpc UnlinkResources(LinkResourcesRequest) returns (Empty);
}


enum StatusCode {
  SUCCEED = 0;
  UNAUTHORIZED = 1;
}

// Models
message Empty {
  StatusCode status_code = 1;
}

message ResourceTypeKey {
  string namespace = 1;
  string type = 2;
}

message ResourceType {
  ResourceTypeKey key = 1;
  string description = 2;
}

message PermissionType {
  string type = 1;
  string description = 2;
}

message PermissionGraphNode {
  string permission_type = 1;
  ResourceTypeKey resource_type_key = 2;
}

message ResourceGraphNode {
  ResourceTypeKey resource_type_key = 1;
  int64 resource_id = 2;
}

message PermissionBinding {
  string permission_type = 1;
  ResourceTypeKey resource_type_key = 2;
  int64 user_id = 3;
  int64 resource_id = 4;
}


// Data Transfer Objects
message FindResourceTypesRequest {
  string namespace = 1;
  string type = 2;
}

message ResourceTypes {
  repeated ResourceType resource_types = 1;
}

message DeletePermissionTypeRequest {
  string type = 1;
}

message FindPermissionTypesRequest {
  string type = 1;
}

message PermissionTypes {
  repeated PermissionType permission_types = 1;
}

message HasPermissionResponse {
  // Need more discussions on error handling
  // 1. when user_id not present, returns false also
  // 2. when permission not present, returns false also
  bool has_permission = 1;
}

message LinkPermissionsRequest {
  PermissionGraphNode from = 1;
  PermissionGraphNode to = 2;
}

message LinkResourcesRequest {
  ResourceGraphNode from = 1;
  ResourceGraphNode to = 2;
}