apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: staging
  name: cloud
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secrets-read-role
  data:
    - name: jwt-signing-key
      key: kv/data/secrets/staging/cloud
      property: jwt-signing-key
    - name: google-client-id
      key: kv/data/secrets/staging/cloud
      property: google-client-id
    - name: google-client-secret
      key: kv/data/secrets/staging/cloud
      property: google-client-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: cloud
  labels:
    app: cloud
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: cloud
          image: registry.digitalocean.com/teamyapp/cloud-staging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: cloud
                  key: jwt-signing-key
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cloud
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloud
                  key: google-client-secret
            - name: ACCESS_TOKEN_TTL
              value: 168h
            - name: GEN_RANGE_SIZE
              value: "100"
            - name: WEB_API_BASE_URL
              value: https://cloud.staging.teamyapp.com
            - name: WEB_API_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: cloud
spec:
  selector:
    app: cloud
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: staging
  name: cloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cloud.staging.teamyapp.com`)
      services:
        - kind: Service
          name: cloud
          namespace: staging
          port: 80
          passHostHeader: true
  tls:
    secretName: teamy-cert
