// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: app/api/proto/authorization.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationClient interface {
	HasPermission(ctx context.Context, in *HasPermissionRequest, opts ...grpc.CallOption) (*HasPermissionResponse, error)
	RegisterResourceRelation(ctx context.Context, in *RegisterResourceRelationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnregisterResourceRelation(ctx context.Context, in *UnregisterResourceRelationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterUserGroup(ctx context.Context, in *RegisterUserGroupRequest, opts ...grpc.CallOption) (*RegisterUserGroupResponse, error)
	UnregisterUserGroup(ctx context.Context, in *UnregisterUserGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type authorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationClient(cc grpc.ClientConnInterface) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) HasPermission(ctx context.Context, in *HasPermissionRequest, opts ...grpc.CallOption) (*HasPermissionResponse, error) {
	out := new(HasPermissionResponse)
	err := c.cc.Invoke(ctx, "/Authorization/HasPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) RegisterResourceRelation(ctx context.Context, in *RegisterResourceRelationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Authorization/RegisterResourceRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) UnregisterResourceRelation(ctx context.Context, in *UnregisterResourceRelationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Authorization/UnregisterResourceRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) RegisterUserGroup(ctx context.Context, in *RegisterUserGroupRequest, opts ...grpc.CallOption) (*RegisterUserGroupResponse, error) {
	out := new(RegisterUserGroupResponse)
	err := c.cc.Invoke(ctx, "/Authorization/RegisterUserGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) UnregisterUserGroup(ctx context.Context, in *UnregisterUserGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Authorization/UnregisterUserGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
// All implementations must embed UnimplementedAuthorizationServer
// for forward compatibility
type AuthorizationServer interface {
	HasPermission(context.Context, *HasPermissionRequest) (*HasPermissionResponse, error)
	RegisterResourceRelation(context.Context, *RegisterResourceRelationRequest) (*emptypb.Empty, error)
	UnregisterResourceRelation(context.Context, *UnregisterResourceRelationRequest) (*emptypb.Empty, error)
	RegisterUserGroup(context.Context, *RegisterUserGroupRequest) (*RegisterUserGroupResponse, error)
	UnregisterUserGroup(context.Context, *UnregisterUserGroupRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAuthorizationServer()
}

// UnimplementedAuthorizationServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServer struct {
}

func (UnimplementedAuthorizationServer) HasPermission(context.Context, *HasPermissionRequest) (*HasPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPermission not implemented")
}
func (UnimplementedAuthorizationServer) RegisterResourceRelation(context.Context, *RegisterResourceRelationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterResourceRelation not implemented")
}
func (UnimplementedAuthorizationServer) UnregisterResourceRelation(context.Context, *UnregisterResourceRelationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterResourceRelation not implemented")
}
func (UnimplementedAuthorizationServer) RegisterUserGroup(context.Context, *RegisterUserGroupRequest) (*RegisterUserGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserGroup not implemented")
}
func (UnimplementedAuthorizationServer) UnregisterUserGroup(context.Context, *UnregisterUserGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterUserGroup not implemented")
}
func (UnimplementedAuthorizationServer) mustEmbedUnimplementedAuthorizationServer() {}

// UnsafeAuthorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServer will
// result in compilation errors.
type UnsafeAuthorizationServer interface {
	mustEmbedUnimplementedAuthorizationServer()
}

func RegisterAuthorizationServer(s grpc.ServiceRegistrar, srv AuthorizationServer) {
	s.RegisterService(&Authorization_ServiceDesc, srv)
}

func _Authorization_HasPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).HasPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/HasPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).HasPermission(ctx, req.(*HasPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_RegisterResourceRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterResourceRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).RegisterResourceRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/RegisterResourceRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).RegisterResourceRelation(ctx, req.(*RegisterResourceRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_UnregisterResourceRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterResourceRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).UnregisterResourceRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/UnregisterResourceRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).UnregisterResourceRelation(ctx, req.(*UnregisterResourceRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_RegisterUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).RegisterUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/RegisterUserGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).RegisterUserGroup(ctx, req.(*RegisterUserGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_UnregisterUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterUserGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).UnregisterUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authorization/UnregisterUserGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).UnregisterUserGroup(ctx, req.(*UnregisterUserGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorization_ServiceDesc is the grpc.ServiceDesc for Authorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasPermission",
			Handler:    _Authorization_HasPermission_Handler,
		},
		{
			MethodName: "RegisterResourceRelation",
			Handler:    _Authorization_RegisterResourceRelation_Handler,
		},
		{
			MethodName: "UnregisterResourceRelation",
			Handler:    _Authorization_UnregisterResourceRelation_Handler,
		},
		{
			MethodName: "RegisterUserGroup",
			Handler:    _Authorization_RegisterUserGroup_Handler,
		},
		{
			MethodName: "UnregisterUserGroup",
			Handler:    _Authorization_UnregisterUserGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/api/proto/authorization.proto",
}
