// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/app/dao"
	"github.com/teamyapp/cloud/app/dao/sqldb"
	"github.com/teamyapp/cloud/app/gen"
	"github.com/teamyapp/cloud/app/oauth"
	"github.com/teamyapp/cloud/app/service"
	"github.com/teamyapp/cloud/app/storage"
	"github.com/teamyapp/cloud/libs/env"
	"github.com/teamyapp/cloud/libs/network"
	"github.com/teamyapp/cloud/libs/security"
	"github.com/teamyapp/cloud/libs/telemetry"
	"github.com/teamyapp/cloud/libs/web"
	"time"
)

// Injectors from wire.go:

func InitTelemetryAPI(logger telemetry.Logger) *api.Telemetry {
	apiTelemetry := api.NewTelemetry(logger)
	return apiTelemetry
}

func InitIdentityAPI(logger telemetry.Logger, sqlDB *sql.DB, oauthProviders OAuthProviders, accessTokenTTL AccessTokenTTL, jwtSigningKey JWTSigningKey, genRangeSize GenRangeSize) (api.Identity, error) {
	signInSession := sqldb.NewSignInSession(sqlDB)
	userLink := sqldb.NewUserLink(sqlDB)
	serviceAccount := sqldb.NewServiceAccount(sqlDB)
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(logger, allocatedRange, genRangeSize)
	jwtAuthority := newJWTAuthority(logger, jwtSigningKey)
	identity, err := newIdentityService(logger, signInSession, userLink, serviceAccount, uniqueNumberFactory, jwtAuthority, oauthProviders, accessTokenTTL)
	if err != nil {
		return api.Identity{}, err
	}
	apiIdentity := api.NewIdentity(logger, identity)
	return apiIdentity, nil
}

func InitGeneratorAPI(logger telemetry.Logger, sqlDB *sql.DB, genRangeSize GenRangeSize) (api.Generator, error) {
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(logger, allocatedRange, genRangeSize)
	generator := api.NewGenerator(logger, uniqueNumberFactory)
	return generator, nil
}

func InitAuthorizationAPI(logger telemetry.Logger, sqlDB *sql.DB, genRangeSize GenRangeSize) (api.Authorization, error) {
	resourceRelation := sqldb.NewResourceRelation(sqlDB)
	userGroupMember := sqldb.NewUserGroupMember(sqlDB)
	permission := sqldb.NewPermission(sqlDB)
	operationRelation := sqldb.NewOperationRelation(sqlDB)
	operation := sqldb.NewOperation(sqlDB)
	resourceType := sqldb.NewResourceType(sqlDB)
	resource := sqldb.NewResource(sqlDB)
	userGroup := sqldb.NewUserGroup(sqlDB)
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(logger, allocatedRange, genRangeSize)
	authorization, err := service.NewAuthorization(logger, resourceRelation, userGroupMember, permission, operationRelation, operation, resourceType, resource, userGroup, uniqueNumberFactory)
	if err != nil {
		return api.Authorization{}, err
	}
	apiAuthorization := api.NewAuthorization(logger, authorization)
	return apiAuthorization, nil
}

func InitFileAPI(logger telemetry.Logger, env2 env.Environment, sqlDB *sql.DB, genRangeSize GenRangeSize, s3Endpoint S3Endpoint, s3AccessKeyID S3AccessKeyID, s3AccessKey S3AccessKey, s3BucketName S3BucketName) (api.File, error) {
	s3Bucket, err := newS3Bucket(logger, s3Endpoint, s3AccessKeyID, s3AccessKey, s3BucketName, env2)
	if err != nil {
		return api.File{}, err
	}
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(logger, allocatedRange, genRangeSize)
	uploadSession := sqldb.NewUploadSession(sqlDB)
	fileMetadata := sqldb.NewFileMetadata(sqlDB)
	chunkMetadata := sqldb.NewChunkMetadata(sqlDB)
	file, err := service.NewFile(logger, s3Bucket, uniqueNumberFactory, uploadSession, fileMetadata, chunkMetadata)
	if err != nil {
		return api.File{}, err
	}
	apiFile := api.NewFile(logger, file)
	return apiFile, nil
}

func InitGitHubOAuthProvider(logger telemetry.Logger, webAPIBaseURL WebAPIBaseURL, clientID ClientID, clientSecret ClientSecret) oauth.GitHub {
	socket := network.NewSocket()
	client := web.NewHTTPClient(socket)
	gitHub := newGithubOAuthProvider(client, webAPIBaseURL, clientID, clientSecret)
	return gitHub
}

func InitGoogleOAuthProvider(logger telemetry.Logger, webAPIBaseURL WebAPIBaseURL, jwtSigningKey JWTSigningKey, clientID ClientID, clientSecret ClientSecret) oauth.Google {
	socket := network.NewSocket()
	client := web.NewHTTPClient(socket)
	jwtAuthority := newJWTAuthority(logger, jwtSigningKey)
	google := newGoogleOAuthProvider(client, jwtAuthority, webAPIBaseURL, clientID, clientSecret)
	return google
}

func InitSlackOAuthProvider(logger telemetry.Logger, webAPIBaseURL WebAPIBaseURL, jwtSigningKey JWTSigningKey, clientID ClientID, clientSecret ClientSecret) oauth.Slack {
	socket := network.NewSocket()
	client := web.NewHTTPClient(socket)
	jwtAuthority := newJWTAuthority(logger, jwtSigningKey)
	slack := newSlackOAuthProvider(client, jwtAuthority, webAPIBaseURL, clientID, clientSecret)
	return slack
}

// wire.go:

type OAuthProviders []oauth.Provider

type AccessTokenTTL time.Duration

type GenRangeSize uint64

type JWTSigningKey string

type WebAPIBaseURL string

type ClientID string

type ClientSecret string

type S3Endpoint string

type S3AccessKeyID string

type S3AccessKey string

type S3BucketName string

var daoSet = wire.NewSet(wire.Bind(new(dao.UserLink), new(sqldb.UserLink)), wire.Bind(new(dao.AllocatedRange), new(sqldb.AllocatedRange)), wire.Bind(new(dao.SignInSession), new(sqldb.SignInSession)), wire.Bind(new(dao.ServiceAccount), new(sqldb.ServiceAccount)), wire.Bind(new(dao.OperationRelation), new(sqldb.OperationRelation)), wire.Bind(new(dao.Operation), new(sqldb.Operation)), wire.Bind(new(dao.UserGroup), new(sqldb.UserGroup)), wire.Bind(new(dao.UserGroupMember), new(sqldb.UserGroupMember)), wire.Bind(new(dao.Permission), new(sqldb.Permission)), wire.Bind(new(dao.ResourceType), new(sqldb.ResourceType)), wire.Bind(new(dao.Resource), new(sqldb.Resource)), wire.Bind(new(dao.ResourceRelation), new(sqldb.ResourceRelation)), wire.Bind(new(dao.UploadSession), new(sqldb.UploadSession)), wire.Bind(new(dao.FileMetadata), new(sqldb.FileMetadata)), wire.Bind(new(dao.ChunkMetadata), new(sqldb.ChunkMetadata)), sqldb.NewAllocatedRange, sqldb.NewUserLink, sqldb.NewSignInSession, sqldb.NewServiceAccount, sqldb.NewOperationRelation, sqldb.NewOperation, sqldb.NewUserGroup, sqldb.NewUserGroupMember, sqldb.NewPermission, sqldb.NewResourceType, sqldb.NewResource, sqldb.NewResourceRelation, sqldb.NewUploadSession, sqldb.NewFileMetadata, sqldb.NewChunkMetadata)

var storageSet = wire.NewSet(wire.Bind(new(storage.MapBackend), new(storage.S3Bucket)), newS3Bucket)

func newS3Bucket(
	logger telemetry.Logger,
	s3Endpoint S3Endpoint,
	s3AccessKeyID S3AccessKeyID,
	s3AccessKey S3AccessKey,
	s3BucketName S3BucketName, env2 env.Environment,

) (storage.S3Bucket, error) {
	return storage.NewS3Bucket(
		logger,
		string(s3Endpoint),
		string(s3AccessKeyID),
		string(s3AccessKey), env2, string(s3BucketName))
}

func newGithubOAuthProvider(
	httpClient web.HTTPClient,
	webAPIBaseURL WebAPIBaseURL,
	clientID ClientID,
	clientSecret ClientSecret,
) oauth.GitHub {
	return oauth.NewGitHub(httpClient, string(webAPIBaseURL), string(clientID), string(clientSecret))
}

func newGoogleOAuthProvider(
	httpClient web.HTTPClient,
	jwtAuthority security.JWTAuthority,
	webAPIBaseURL WebAPIBaseURL,
	clientID ClientID,
	clientSecret ClientSecret,
) oauth.Google {
	return oauth.NewGoogle(httpClient, jwtAuthority, string(webAPIBaseURL), string(clientID), string(clientSecret))
}

func newSlackOAuthProvider(
	httpClient web.HTTPClient,
	jwtAuthority security.JWTAuthority,
	webAPIBaseURL WebAPIBaseURL,
	clientID ClientID,
	clientSecret ClientSecret,
) oauth.Slack {
	return oauth.NewSlack(httpClient, jwtAuthority, string(webAPIBaseURL), string(clientID), string(clientSecret))
}

func newJWTAuthority(logger telemetry.Logger, signingKey JWTSigningKey) security.JWTAuthority {
	return security.NewJWTAuthority(logger, string(signingKey))
}

func newUniqueNumberGenFactory(
	logger telemetry.Logger,
	allocatedRangeDao dao.AllocatedRange,
	genRangeSize GenRangeSize) gen.UniqueNumberFactory {
	return gen.NewUniqueNumberFactory(logger, allocatedRangeDao, uint64(genRangeSize))
}

func newIdentityService(
	logger telemetry.Logger,
	signInSessionDao dao.SignInSession,
	userLinkDao dao.UserLink,
	serviceAccountDao dao.ServiceAccount,
	uniqueNumberFactory gen.UniqueNumberFactory,
	jwtAuthority security.JWTAuthority,
	oauthProviders OAuthProviders,
	accessTokenTLL AccessTokenTTL,
) (service.Identity, error) {
	return service.NewIdentity(
		logger,
		signInSessionDao,
		userLinkDao,
		serviceAccountDao,
		uniqueNumberFactory,
		jwtAuthority,
		oauthProviders, time.Duration(accessTokenTLL))
}
