// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"time"

	"github.com/google/wire"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/app/config"
	"github.com/teamyapp/cloud/app/dao"
	"github.com/teamyapp/cloud/app/dao/dao_test"
	"github.com/teamyapp/cloud/app/dao/sqldb"
	"github.com/teamyapp/cloud/app/entity"
	"github.com/teamyapp/cloud/app/gen"
	"github.com/teamyapp/cloud/app/oauth"
	"github.com/teamyapp/cloud/app/service"
	"github.com/teamyapp/cloud/app/storage"
	"github.com/teamyapp/cloud/libs/security"
)

// Injectors from wire.go:

func InitGoogleOAuthProvider(webAPIBaseURL WebAPIBaseURL, jwtSigningKey JWTSigningKey, clientID ClientID, clientSecret ClientSecret) oauth.Google {
	jwtAuthority := newJWTAuthority(jwtSigningKey)
	google := newGoogleOAuthProvider(jwtAuthority, webAPIBaseURL, clientID, clientSecret)
	return google
}

func InitIdentityAPI(sqlDB *sql.DB, oauthProviders OAuthProviders, accessTokenTTL AccessTokenTTL, jwtSigningKey JWTSigningKey, genRangeSize GenRangeSize) (api.Identity, error) {
	signInSession := sqldb.NewSignInSession(sqlDB)
	userLink := sqldb.NewUserLink(sqlDB)
	serviceAccount := sqldb.NewServiceAccount(sqlDB)
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(allocatedRange, genRangeSize)
	jwtAuthority := newJWTAuthority(jwtSigningKey)
	identity, err := newIdentityService(signInSession, userLink, serviceAccount, uniqueNumberFactory, jwtAuthority, oauthProviders, accessTokenTTL)
	if err != nil {
		return api.Identity{}, err
	}
	apiIdentity := api.NewIdentity(identity)
	return apiIdentity, nil
}

func InitGeneratorAPI(sqlDB *sql.DB, genRangeSize GenRangeSize) (api.Generator, error) {
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(allocatedRange, genRangeSize)
	generator := api.NewGenerator(uniqueNumberFactory)
	return generator, nil
}

func InitAuthorizationAPI(sqlDB *sql.DB) (api.Authorization, error) {
	resourceRelation := sqldb.NewResourceRelation(sqlDB)
	userGroupMember := newUserGroupMember()
	permission := newPermission()
	operationRelation := newOperationRelation()
	resourceType := sqldb.NewResourceType(sqlDB)
	resource := sqldb.NewResource(sqlDB)
	authorization := service.NewAuthorization(resourceRelation, userGroupMember, permission, operationRelation, resourceType, resource)
	apiAuthorization := api.NewAuthorization(authorization)
	return apiAuthorization, nil
}

func InitFileAPI(env config.Environment, sqlDB *sql.DB, genRangeSize GenRangeSize, s3Endpoint S3Endpoint, s3AccessKeyID S3AccessKeyID, s3AccessKey S3AccessKey, s3BucketName S3BucketName) (api.File, error) {
	s3Bucket, err := newS3Bucket(s3Endpoint, s3AccessKeyID, s3AccessKey, s3BucketName, env)
	if err != nil {
		return api.File{}, err
	}
	allocatedRange := sqldb.NewAllocatedRange(sqlDB)
	uniqueNumberFactory := newUniqueNumberGenFactory(allocatedRange, genRangeSize)
	uploadSession := sqldb.NewUploadSession(sqlDB)
	fileMetadata := sqldb.NewFileMetadata(sqlDB)
	chunkMetadata := sqldb.NewChunkMetadata(sqlDB)
	file, err := service.NewFile(s3Bucket, uniqueNumberFactory, uploadSession, fileMetadata, chunkMetadata)
	if err != nil {
		return api.File{}, err
	}
	apiFile := api.NewFile(file)
	return apiFile, nil
}

// wire.go:

type OAuthProviders []oauth.Provider

type AccessTokenTTL time.Duration

type GenRangeSize uint64

type JWTSigningKey string

type WebAPIBaseURL string

type ClientID string

type ClientSecret string

var daoSet = wire.NewSet(wire.Bind(new(dao.UserLink), new(sqldb.UserLink)), wire.Bind(new(dao.AllocatedRange), new(sqldb.AllocatedRange)), wire.Bind(new(dao.SignInSession), new(sqldb.SignInSession)), wire.Bind(new(dao.ServiceAccount), new(sqldb.ServiceAccount)), wire.Bind(new(dao.OperationRelation), new(dao_test.OperationRelation)), wire.Bind(new(dao.UserGroupMember), new(dao_test.UserGroupMember)), wire.Bind(new(dao.Permission), new(dao_test.Permission)), wire.Bind(new(dao.ResourceType), new(sqldb.ResourceType)), wire.Bind(new(dao.Resource), new(sqldb.Resource)), wire.Bind(new(dao.ResourceRelation), new(sqldb.ResourceRelation)), wire.Bind(new(dao.UploadSession), new(sqldb.UploadSession)), wire.Bind(new(dao.FileMetadata), new(sqldb.FileMetadata)), wire.Bind(new(dao.ChunkMetadata), new(sqldb.ChunkMetadata)), sqldb.NewAllocatedRange, sqldb.NewUserLink, sqldb.NewSignInSession, sqldb.NewServiceAccount, newOperationRelation,
	newUserGroupMember,
	newPermission, sqldb.NewResourceType, sqldb.NewResource, sqldb.NewResourceRelation, sqldb.NewUploadSession, sqldb.NewFileMetadata, sqldb.NewChunkMetadata,
)

var storageSet = wire.NewSet(wire.Bind(new(storage.MapBackend), new(storage.S3Bucket)), newS3Bucket)

type S3Endpoint string

type S3AccessKeyID string

type S3AccessKey string

type S3BucketName string

func newS3Bucket(
	s3Endpoint S3Endpoint,
	s3AccessKeyID S3AccessKeyID,
	s3AccessKey S3AccessKey,
	s3BucketName S3BucketName,
	env config.Environment,
) (storage.S3Bucket, error) {
	return storage.NewS3Bucket(string(s3Endpoint), string(s3AccessKeyID), string(s3AccessKey), env, string(s3BucketName))
}

func newGoogleOAuthProvider(
	jwtAuthority security.JWTAuthority,
	webAPIBaseURL WebAPIBaseURL,
	clientID ClientID,
	clientSecret ClientSecret,
) oauth.Google {
	return oauth.NewGoogle(jwtAuthority, string(webAPIBaseURL), string(clientID), string(clientSecret))
}

func InitGitHubOAuthProvider(
	webAPIBaseURL WebAPIBaseURL,
	clientID ClientID,
	clientSecret ClientSecret,
) oauth.GitHub {
	return oauth.NewGitHub(string(webAPIBaseURL), string(clientID), string(clientSecret))
}

func newJWTAuthority(signingKey JWTSigningKey) security.JWTAuthority {
	return security.NewJWTAuthority(string(signingKey))
}

func newUniqueNumberGenFactory(allocatedRangeDao dao.AllocatedRange, genRangeSize GenRangeSize) gen.UniqueNumberFactory {
	return gen.NewUniqueNumberFactory(allocatedRangeDao, uint64(genRangeSize))
}

func newIdentityService(
	signInSessionDao dao.SignInSession,
	userLinkDao dao.UserLink,
	serviceAccountDao dao.ServiceAccount,
	uniqueNumberFactory gen.UniqueNumberFactory,
	jwtAuthority security.JWTAuthority,
	oauthProviders OAuthProviders,
	accessTokenTLL AccessTokenTTL,
) (service.Identity, error) {
	return service.NewIdentity(
		signInSessionDao,
		userLinkDao,
		serviceAccountDao,
		uniqueNumberFactory,
		jwtAuthority,
		oauthProviders, time.Duration(accessTokenTLL))
}

func newOperationRelation() dao_test.OperationRelation {
	return dao_test.NewOperationRelation(fakeOperationRelationDao)
}

func newUserGroupMember() dao_test.UserGroupMember {
	return dao_test.NewUserGroupMember(fakeUserGroupMemberDao)
}

func newPermission() dao_test.Permission {
	return dao_test.NewPermission(fakePermissionDao)
}

// TODO: replace with sqldb
var fakeOperationRelationDao = []entity.OperationRelation{}

var fakeUserGroupMemberDao = []entity.UserGroupMember{}

var fakePermissionDao = []entity.Permission{}
